/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sebastianatabalesschnitzlerbattleships;

import java.awt.Toolkit;

/**
 *
 * @author Seb
 */
public class BattleShipsLose extends javax.swing.JFrame {

    /**
     * Creates new form BattleShipsLose
     */
    public BattleShipsLose() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    public BattleShipsLose(int n) {
        initComponents();
        LBLShotNum.setText(n + "");
        LBLAccuracy.setText(rounding(16,n)+ "%");
    }
    /**
     * Rounds the score to give an accuracy value rounded.
     * @param n - 16 - How many minimum shots is required to win a game
     * @param d - how many shots were taken
     * @return 
     */
    private double rounding(int n, int d)
    {
        double result = (n/(double)d) * 100;
        result *= 100;
        result = Math.round(result);
        result /= 100;
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLVICTORY = new javax.swing.JLabel();
        LBLShotNum = new javax.swing.JLabel();
        LBLNumOfShot = new javax.swing.JLabel();
        LBLAcc = new javax.swing.JLabel();
        LBLAccuracy = new javax.swing.JLabel();
        BTNExit = new javax.swing.JButton();
        Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DEFEAT");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLVICTORY.setFont(new java.awt.Font("NSimSun", 1, 70)); // NOI18N
        LBLVICTORY.setForeground(new java.awt.Color(153, 0, 0));
        LBLVICTORY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLVICTORY.setText("DEFEAT");
        LBLVICTORY.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(102, 0, 0)));
        getContentPane().add(LBLVICTORY, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        LBLShotNum.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        LBLShotNum.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LBLShotNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 120, 30));

        LBLNumOfShot.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 14)); // NOI18N
        LBLNumOfShot.setForeground(new java.awt.Color(255, 255, 255));
        LBLNumOfShot.setText("Number of Shots:");
        getContentPane().add(LBLNumOfShot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 130, 30));

        LBLAcc.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        LBLAcc.setForeground(new java.awt.Color(255, 255, 255));
        LBLAcc.setText("Accuracy:");
        getContentPane().add(LBLAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        LBLAccuracy.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 14)); // NOI18N
        LBLAccuracy.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LBLAccuracy, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, 20));

        BTNExit.setBackground(new java.awt.Color(255, 51, 51));
        BTNExit.setFont(new java.awt.Font("DejaVu Serif", 0, 18)); // NOI18N
        BTNExit.setForeground(new java.awt.Color(102, 0, 0));
        BTNExit.setText("Exit");
        BTNExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNExitActionPerformed(evt);
            }
        });
        getContentPane().add(BTNExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 270, 110));

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sebastianatabalesschnitzlerbattleships/Images/LoseImage.jpg"))); // NOI18N
        getContentPane().add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -50, 1620, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BTNExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleShipsLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleShipsLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleShipsLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleShipsLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleShipsLose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNExit;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel LBLAcc;
    private javax.swing.JLabel LBLAccuracy;
    private javax.swing.JLabel LBLNumOfShot;
    private javax.swing.JLabel LBLShotNum;
    private javax.swing.JLabel LBLVICTORY;
    // End of variables declaration//GEN-END:variables
}
