/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sebastianatabalesschnitzlerbattleships;

import java.awt.Toolkit;

/**
 *
 * @author Seb
 */
public class BattleShipsMain extends javax.swing.JFrame {

    /**
     * Creates new form BattleShipsMain
     */
    public BattleShipsMain() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png"))); // My Icon :)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLTitle = new javax.swing.JLabel();
        playBTN = new javax.swing.JButton();
        MenuImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SEBASTIAN'S BATTLESHIPS");
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLTitle.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 48)); // NOI18N
        LBLTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sebastianatabalesschnitzlerbattleships/BATTLESHIPS.png"))); // NOI18N
        getContentPane().add(LBLTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        playBTN.setBackground(new java.awt.Color(102, 255, 102));
        playBTN.setForeground(new java.awt.Color(0, 102, 0));
        playBTN.setText("PLAY");
        playBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBTNActionPerformed(evt);
            }
        });
        getContentPane().add(playBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 150, 60));

        MenuImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sebastianatabalesschnitzlerbattleships/Images/MenuArt.jpg"))); // NOI18N
        getContentPane().add(MenuImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Changes the scene to the Placement menu
 * @param evt 
 */
    private void playBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBTNActionPerformed
        this.setVisible(false);
        BattleShipsPlacement scene = new BattleShipsPlacement();
        scene.setVisible(true);
    }//GEN-LAST:event_playBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleShipsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleShipsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleShipsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleShipsMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleShipsMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLTitle;
    private javax.swing.JLabel MenuImage;
    private javax.swing.JButton playBTN;
    // End of variables declaration//GEN-END:variables
}
